repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: typecheck
        name: typecheck
        entry: bash -c 'npm run typecheck'
        language: system
        pass_filenames: false

      - id: lint
        name: lint
        entry: bash -c 'npm run lint'
        language: system
        pass_filenames: false
